variable "location" {}
variable "resource_group_name" {}
variable "plan_name" {}
variable "webapp_name" {}
variable "ai_connection_string" {}
variable "acr_login_server" {}
variable "acr_admin_username" {}
variable "connection_string" {}
variable "law_id" {}
variable "autoscale_name" {}
